project:
  type: website
  resources: 
    - '.htaccess'

execute:
  freeze: auto

website:
  title: "David Sanson"
  site-url: "https://www.davidsanson.com"
  image: "media/david.jpg"
  favicon: "media/favicon.png"
  twitter-card: true
  open-graph: true
  page-footer: |
    © 2026 David Sanson. Created using [Quarto](https://quarto.org/).
  repo-url: https://github.com/dsanson/dsanson.github.io
  repo-actions: [source, issue]
  navbar:
    aria-label: navigation
    left:
      - href: index.md
        text: Home
      - href: research.md
        text: Research 
      - href: stuff.md
        text: Other Stuff
      - href: cv.md
        text: CV

format:
  html:
    highlight-style: a11y
    theme:
      light: 
        - cosmo
        - custom.scss
      dark: 
        - darkly
        - custom.scss
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true

